psswrd_project/pssapp/urls.py
from django.urls import path
from pssapp import views

#template tagging
app_name = 'pssapp'
urlpatterns = [
    path('register/' , views.register , name = 'register'),
    path("user_login/", views.user_login, name="user_login")
]

psswrd_project/psswrd_project/urls.py
from django.contrib import admin
from django.urls import path,include
from pssapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '' , views.index , name='index'),
    path("pssapp/", include('pssapp.urls')),
    path('logout/', views.user_logout, name='logout')
]

psswrd_project/pssapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserPorfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    protfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username
     

psswrd_project/pssapp/forms.py
from django import forms
from django.contrib.auth.models import User
from pssapp.models import UserPorfileInfo

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
class UserPorfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserPorfileInfo
        fields = ('protfolio_site', 'profile_pic')
        

psswrd_project/pssapp/views.py
from django.shortcuts import render
from pssapp.forms import Userform , UserPorfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index (request):
    return render (request , 'pssapp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    
    if request.method == "POST" :
        user_form = Userform(data=request.POST)
        profile_form = UserPorfileInfoForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user =  user_form.save()
            #user = request.user
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit = False)
            profile.user = user
            
            if 'profile_pic' in request.FILES :
                profile.profile_pic = request.FILES['profile_pic']
                
            profile.save()
            
            registered = True
        else:
            print(user_form.errors , profile_form.errors)
    else:
        user_form = Userform()
        profile_form = UserPorfileInfoForm()
        
    return render(request , 'pssapp/registration.html' , {
                            'user_form' : user_form ,
                            'profile_form' : profile_form ,
                            'registered' : registered })
    
def user_login (request):
    if request.method == "POST" :
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        
        if user :
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            return HttpResponse('invalid login details supplied')
    else:
        return render(request , 'pssapp/login.html' , {})
    

psswrd_project/templates/pssapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar_default navbar_static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">s2mh</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'pssapp:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'pssapp:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock%}
    </div>
</body>
</html>

psswrd_project/templates/pssapp/index.html
{% extends 'pssapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Registration Example</h1>
</div>

{% endblock %}

psswrd_project/templates/pssapp/login.html
{% extends 'pssapp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'pssapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Enter Password">
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

psswrd_project/templates/pssapp/registration.html
{% extends 'pssapp/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thanks For Registering</h1>
    {%else %}
        <h1>Register Here</h1>
        <h3>Fill out the form :</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}